# Generated by Django 3.2.8 on 2022-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='User', max_length=15)),
                ('phno', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
